### ISSUE TITLE
Pre-trained Models

### ISSUE THREAD

**Issue by soraozawa** [PointCloudYC/ResPointNet2#4]
@PointCloudYC 
Hello.
My name is Sora Ozawa from the University of Tokyo.
I have been reading your paper and using it as a reference for my research.
When I step on the link of the trained model in the README, I get a Not Found error, and it seems that the link is broken.
https://github.com/PointCloudYC/ResPointNet2#pre-trained-models

Please update this link

**Comment by PointCloudYC** [comment]
You can train the model first, then you can obtain checkpoints, then change the new checkpoint path.

**Comment by soraozawa** [comment]
Thank you very much. I will attempt to train the model in my environment.
